[package]
name = "opencv-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.0", features=["derive"] }
opencv = { workspace = true }
tokio = { workspace = true }

openh264 = { git="https://github.com/sdwoodbury/openh264-rs", rev="36abe7e7349c890684457fabaf5d90cb4b716cec" }

x264 = { version = "0.5" }

rav1e = { version = "0.6", default-features =false }
av-data = { workspace = true }
libaom = { workspace = true }