[package]
name = "opencv-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.9", features=["derive"] }
opencv = { version = "0.82", features=["clang-runtime"] }
x264 = { git="https://github.com/quadrupleslap/x264", rev="3968f6e42028175b70a6967e86550ff604f826ac" }
tokio = { version = "1.29.0", features = ["full"] }