[package]
name = "wasm-ipfs-identity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Response', 'Window', "console"] }
js-sys = "0.3.69"
console_error_panic_hook = "0.1.7"
serde_json.workspace = true
serde.workspace = true
warp.workspace = true
warp-ipfs.workspace = true
tracing-wasm = "0.2.1"