mod aom;
mod h264;
mod rav1e;
mod x264;
pub use crate::encode::aom::encode_aom;
pub use crate::encode::h264::encode_h264;
pub use crate::encode::rav1e::encode_rav1e;
pub use crate::encode::x264::encode_x264;

use clap::Parser;

// transforms the input file to h264
#[derive(Parser, Debug)]
pub struct Args {
    /// an mp4 file generated by opencv
    pub input: String,
    /// name of the file to save
    pub output: String,
    /// The codec to use
    pub codec: CodecTypes,
    /// Optional parameter. defaults to Lossy.
    /// NotLossy doubles the size of each frame so that converting to YUV420
    /// doesn't lose any chromiance information.
    pub encoding_type: Option<EncodingType>,
}

#[derive(Debug, Clone, clap::ValueEnum)]
pub enum CodecTypes {
    /// OpenH264
    H264,
    /// x264
    X264,
    /// av1 (rav1e)
    RAV1E,
    /// av1 (aom)
    AOM,
}

#[derive(Debug, Clone, clap::ValueEnum)]
pub enum EncodingType {
    Lossy,
    NotLossy,
}
