[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
warp-ipfs = { path = "../" }
bytes.workspace = true
cbor4ii.workspace = true
rust-ipfs = { workspace = true, features = ["webrtc_transport", "experimental_stream"] }
libipld.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
futures.workspace = true
async-trait.workspace = true
async-stream.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
either = { workspace = true, features = ["serde"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

chrono = { workspace = true }

void.workspace = true

clap = { version = "4.4", features = ["derive"] }
zeroize.workspace = true
dotenv = "0.15"
base64 = "0.21"

bs58.workspace = true

tokio = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["net"] }

