[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
rust-ipfs.workspace = true
libipld.workspace = true
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
zeroize.workspace = true
x25519-dalek.workspace = true
ed25519-dalek.workspace = true
curve25519-dalek.workspace = true
sha2.workspace = true
aes-gcm = { workspace = true, features = ["stream"] }
rand.workspace = true
dotenv = "0.15"
base64 = "0.21"
uuid.workspace = true
bincode.workspace = true
bytes.workspace = true