[package]
name = "warp-blink-wrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
async-stream.workspace = true
bytes.workspace = true
bs58.workspace = true
chrono.workspace = true
derive_more.workspace = true
futures.workspace = true
rust-ipfs.workspace = true
libipld.workspace = true
log = "0.4.17"
once_cell.workspace = true
opus = "0.3.0"
uuid.workspace = true
rand.workspace = true
ringbuf = "0.3"
serde.workspace = true
serde_cbor.workspace = true
tokio.workspace = true
warp = { path = "../../warp" }
webrtc = "0.6.0"
# if this fails to build on mac, run this: `brew install autoconf automake libtool pkg-config`
webrtc-audio-processing = { version = "0.4.0", features = ["bundled"] }

# media 
cpal = "0.15.0"

[build-dependencies]
cbindgen = "0.23"

[features]
build-header = []