[package]
name = "fs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-io = { workspace = true}
futures-util = { workspace = true, features = ["io"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["compat"]}
tokio-stream = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo = { workspace = true }

