

language = "C"

cpp_compat = true
include_guard = "_WARP_MP_SOLANA_H_"

[export]

exclude = ["FFIError", "FFIResult_String"]

[parse]
parse_deps = true
clean = false
include = ["warp"]

[parse.expand]
crates = ["warp", "warp-mp-solana"]

